index_type = "unsigned int"
enum_type = "oly::rendering::FrameFormat"
default = 0

[[enum]]
label = "Single"
index = 0
enum = 0x0
comment = "FrameFormat::Single"

[[enum]]
label = "Auto"
index = 1
enum = 0x1
comment = "FrameFormat::Auto"
