[context]
window_hint               = {}
window                    = { "width" = 1440, "height" = 1080, "title" = "Olympian Engine" }
"gamepads"                = 1
"signals"                 = [ "assets/signals.toml" ]
logger                    = { "logfile" = "Olympian.log", "append" = true, "console" = true }
sprite_batch              = { "initial sprites" = 50, "new textures" = 10 }
polygon_batch             = { "primitives" = 100 }
ellipse_batch             = { "ellipses" = 100 }
"tileset registries"      = [ "assets/grass_tileset.toml" ]
"font face registries"    = [ "assets/fonts.toml" ]
"font atlas registries"   = [ "assets/fonts.toml" ]
text_batch                = { "initial glyphs" = 1000, "new textures" = 10 }
