index_type = "unsigned int"
enum_type = "oly::input::Axis2DModifier::Conversion"
default = 0

[[enum]]
label = "None"
index = 0
enum = 0x0
comment = "Conversion::None"

[[enum]]
label = "To 0D (X)"
index = 1
enum = 0x1
comment = "Conversion::To0D_X"

[[enum]]
label = "To 0D (Y)"
index = 2
enum = 0x2
comment = "Conversion::To0D_Y"

[[enum]]
label = "To 0D (X or Y)"
index = 3
enum = 0x3
comment = "Conversion::To0D_XY"

[[enum]]
label = "To 1D (X)"
index = 4
enum = 0x4
comment = "Conversion::To1D_X"

[[enum]]
label = "To 1D (Y)"
index = 5
enum = 0x5
comment = "Conversion::To1D_Y"

[[enum]]
label = "To 1D (Magnitude)"
index = 6
enum = 0x6
comment = "Conversion::To1D_XY"

[[enum]]
label = "To 3D (Z => 0)"
index = 7
enum = 0x7
comment = "Conversion::To3D_0"

[[enum]]
label = "To 3D (Z => 1)"
index = 8
enum = 0x8
comment = "Conversion::To3D_1"
