index_type = "unsigned int"
enum_type = "oly::input::SignalBindingType"
default = 0

[[enum]]
label = "Key"
index = 0
enum = 0x0
comment = "SignalBindingType::Key"

[[enum]]
label = "Mouse Button"
index = 1
enum = 0x1
comment = "SignalBindingType::MouseButton"

[[enum]]
label = "Gamepad Button"
index = 2
enum = 0x2
comment = "SignalBindingType::GamepadButton"

[[enum]]
label = "Gamepad Axis 1D"
index = 3
enum = 0x3
comment = "SignalBindingType::GamepadAxis1D"

[[enum]]
label = "Gamepad Axis 2D"
index = 4
enum = 0x4
comment = "SignalBindingType::GamepadAxis2D"

[[enum]]
label = "Cursor Position"
index = 5
enum = 0x5
comment = "SignalBindingType::CursorPos"

[[enum]]
label = "Scroll"
index = 6
enum = 0x6
comment = "SignalBindingType::Scroll"
