index_type = "unsigned int"
enum_type = "oly::input::ModifierBase::Swizzle"
default = 0

[[enum]]
label = "None"
index = 0
enum = 0x0
comment = "Swizzle::None"

[[enum]]
label = "YX"
index = 1
enum = 0x1
comment = "Swizzle::YX"

[[enum]]
label = "XZY"
index = 2
enum = 0x2
comment = "Swizzle::XZY"

[[enum]]
label = "YXZ"
index = 3
enum = 0x3
comment = "Swizzle::YXZ"

[[enum]]
label = "YZX"
index = 4
enum = 0x4
comment = "Swizzle::YZX"

[[enum]]
label = "ZXY"
index = 5
enum = 0x5
comment = "Swizzle::ZXY"

[[enum]]
label = "ZYX"
index = 6
enum = 0x6
comment = "Swizzle::ZYX"
