index_type = "unsigned int"
enum_type = "oly::rendering::PolyCompositeMethod"
default = 0

[[enum]]
label = "N-Gon"
index = 0
enum = 0x0
comment = "PolyCompositeMethod::Ngon"

[[enum]]
label = "Bordered N-Gon"
index = 1
enum = 0x1
comment = "PolyCompositeMethod::BorderedNgon"

[[enum]]
label = "Convex Decomposition"
index = 2
enum = 0x2
comment = "PolyCompositeMethod::ConvexDecomposition"
