index_type = "unsigned int"
enum_type = "oly::StorageMode"
default = 0

[[enum]]
label = "Discard"
index = 0
enum = 0x0
comment = "StorageMode::Discard"

[[enum]]
label = "Keep"
index = 1
enum = 0x1
comment = "StorageMode::Keep"
