[ellipse]
transform = { "position" = [ -300, 0 ], "scale" = [150, 150] }
"width"  = 2
"height" = 1
"border" = 0.3
"fill inner color"   = [ 1.0, 0.9, 0.8, 0.5 ]
"fill outer color"   = [ 1.0, 0.6, 0.2, 1.0 ]
"border inner color" = [ 0.2, 0.6, 1.0, 1.0 ]
"border outer color" = [ 0.8, 0.9, 1.0, 1.0 ]
