#meta type="font_defaults"

[font_face]
storage = "keep"

[font_atlas]
storage = "discard"
font_size = 32.0
min_filter = 9728
mag_filter = 9728
generate_mipmaps = false
common_buffer_preset = "common"
common_buffer = ""
use_common_buffer_preset = true
