#meta type="texture_defaults"

[raster]
storage = "discard"
generate_mipmaps = false
min_filter = 9728
mag_filter = 9728
wrap_s = 33071
wrap_t = 33071

[svg]
image_storage = "discard"
abstract_storage = "discard"
generate_mipmaps = "off"
svg_scale = 1.0
min_filter = 9728
mag_filter = 9728
wrap_s = 33071
wrap_t = 33071
