project_id_stack = []
"project next id" = 2
last_file_dialog_dir = "D:/Projects/Visual Studio/Olympian"
recent = [ "D:/Projects/Visual Studio/Olympian/Tester/Tester.oly",]

[projects]
"D:/Projects/Visual Studio/Olympian/Tester/Tester.oly" = 1
