[poly_composite]
transform = { "position" = [100, -100], "scale" = [150, 150] }
"method" = "bordered ngon"
"points" = [[ 3, -1 ], [ 0, 2 ], [ -3, -1 ], [ 0, 0 ]]
"fill colors" = [[0.9, 0.9, 0.7, 1.0]]
"border colors" = [[0.3, 0.15, 0.0, 1.0]]
"border width" = 0.1
"border pivot" = "middle"
