[poly_composite]
transform = { "position" = [-200, 200], "scale" = [60, 60] }
"method" = "convex decomposition"
"points" = [
	[ -4,  0 ],
	[ -2, -2 ],
	[  0, -2 ],
	[  2, -1 ],
	[  4,  1 ],
	[  2,  3 ],
	[  1,  3 ],
	[ -1,  0 ],
	[ -3,  1 ],
	[ -3,  2 ]
]
