[ngon]
transform = { "position" = [300, 200], "scale" = [200, 200] }
"points" = [
	[      1,      0 ],
	[  0.707,  0.707 ],
	[      0,      1 ],
	[ -0.707,  0.707 ],
	[     -1,      0 ],
	[ -0.707, -0.707 ],
	[      0,     -1 ],
	[  0.707, -0.707 ]
]
"fill colors" = [[0.0, 1.0, 0.0, 0.7]]
"border colors" = [
	[ 0.25,  0.0,  0.5, 1.0 ],
	[  0.0, 0.25, 0.25, 1.0 ],
	[ 0.25,  0.5,  0.0, 1.0 ],
	[  0.5, 0.75, 0.25, 1.0 ],
	[ 0.75,  1.0,  0.5, 1.0 ],
	[  1.0, 0.75, 0.75, 1.0 ],
	[ 0.75,  0.5,  1.0, 1.0 ],
	[  0.5, 0.25, 0.75, 1.0 ]
]
"bordered" = true
"border width" = 0.05
