[polygon]
"points" = [
	[  1, -1 ],
	[  1,  0 ],
	[  0,  1 ],
	[ -1,  0 ],
	[ -1, -1 ]
]
"colors" = [
	[ 1.0, 1.0, 0.0, 0.5 ],
	[ 1.0, 0.0, 1.0, 0.5 ],
	[ 0.0, 1.0, 1.0, 0.5 ],
	[ 0.0, 0.0, 0.0, 0.5 ],
	[ 1.0, 1.0, 1.0, 0.5 ]
]
transform = { "position" = [-250, 0], "rotation" = -1, "scale" = [320, 160] }
