[polygon]
"points" = [
	[  1, -1 ],
	[  1,  0 ],
	[  0,  1 ],
	[ -1,  0 ],
	[ -1, -1 ]
]
"colors" = [
	[ 1.0, 1.0, 0.0, 1.0 ],
	[ 1.0, 0.0, 1.0, 1.0 ],
	[ 0.0, 1.0, 1.0, 1.0 ],
	[ 0.0, 0.0, 0.0, 1.0 ],
	[ 1.0, 1.0, 1.0, 1.0 ]
]
transform = { "position" = [0, 200], "scale" = [160, 160] }
