index_type = "unsigned int"
enum_type = "GLenum"
default = 0

[[enum]]
label = "Nearest"
index = 0
enum = 0x2600
comment = "GL_NEAREST"

[[enum]]
label = "Linear"
index = 1
enum = 0x2601
comment = "GL_LINEAR"
