index_type = "unsigned int"
enum_type = "GLenum"
default = 0

[[enum]]
label = "Nearest"
index = 0
enum = 0x2600
comment = "GL_NEAREST"

[[enum]]
label = "Linear"
index = 1
enum = 0x2601
comment = "GL_LINEAR"

[[enum]]
label = "Nearest (Nearest Mipmap)"
index = 2
enum = 0x2700
comment = "GL_NEAREST_MIPMAP_NEAREST"

[[enum]]
label = "Linear (Nearest Mipmap)"
index = 3
enum = 0x2701
comment = "GL_LINEAR_MIPMAP_NEAREST"

[[enum]]
label = "Nearest (Linear Mipmap)"
index = 4
enum = 0x2702
comment = "GL_NEAREST_MIPMAP_LINEAR"

[[enum]]
label = "Linear (Linear Mipmap)"
index = 5
enum = 0x2703
comment = "GL_LINEAR_MIPMAP_LINEAR"
