index_type = "unsigned int"
enum_type = "oly::graphics::SVGMipmapGenerationMode"
default = 1

[[enum]]
label = "Auto"
index = 0
enum = 0x0
comment = "SVGMipmapGenerationMode::Auto"

[[enum]]
label = "Off"
index = 1
enum = 0x1
comment = "SVGMipmapGenerationMode::Off"

[[enum]]
label = "Manual"
index = 2
enum = 0x2
comment = "SVGMipmapGenerationMode::Manual"
