index_type = "unsigned int"
enum_type = "GLenum"
default = 0

[[enum]]
label = "Clamp To Edge"
index = 0
enum = 0x812F
comment = "GL_CLAMP_TO_EDGE"

[[enum]]
label = "Clamp To Border"
index = 1
enum = 0x812D
comment = "GL_CLAMP_TO_BORDER"

[[enum]]
label = "Mirrored Repeat"
index = 2
enum = 0x8370
comment = "GL_MIRRORED_REPEAT"

[[enum]]
label = "Repeat"
index = 3
enum = 0x2901
comment = "GL_REPEAT"

[[enum]]
label = "Mirror Clamp To Edge"
index = 4
enum = 0x8743
comment = "GL_MIRROR_CLAMP_TO_EDGE"
