[[key]]
label = "Transformer"
code = "Trfmer"
enum = "Transformer"

[[key]]
label = "Camera Invariant"
code = "CamInv"
enum = "CameraInvariant"

[[key]]
label = "Points"
code = "Points"
enum = "PointsArray"

[[key]]
label = "Colors"
code = "Colors"
enum = "ColorsArray"

[[key]]
label = "Method"
code = "Method"
enum = "Method"

[[key]]
label = "Fill Colors"
code = "FillClrs"
enum = "FillColorsArray"

[[key]]
label = "Border Colors"
code = "BrdClrs"
enum = "BorderColorsArray"

[[key]]
label = "Bordered"
code = "Bordered"
enum = "Bordered"

[[key]]
label = "Border Width"
code = "BorderW"
enum = "BorderWidth"

[[key]]
label = "Border Pivot"
code = "BorderP"
enum = "BorderPivot"
