[[key]]
label = "Signals"
code = "Signal"
enum = "SignalArray"

[[key]]
label = "ID"
code = "ID"
enum = "ID"

[[key]]
label = "Binding"
code = "Binding"
enum = "Binding"

[[key]]
label = "Mappings"
code = "Mapping"
enum = "MappingArray"

[[key]]
label = "Mapped Signal List"
code = "Signals"
enum = "MappedSignalList"

[[key]]
label = "Key"
code = "Key"
enum = "Key"

[[key]]
label = "Button"
code = "Button"
enum = "Button"

[[key]]
label = "Axis 1D"
code = "Axis1D"
enum = "Axis1D"

[[key]]
label = "Axis 2D"
code = "Axis2D"
enum = "Axis2D"

[[key]]
label = "Deadzone"
code = "Deadzone"
enum = "Deadzone"

[[key]]
label = "Required Mods"
code = "ReqMods"
enum = "RequiredMods"

[[key]]
label = "Forbidden Mods"
code = "BanMods"
enum = "ForbiddenMods"

[[key]]
label = "Modifier"
code = "Modifier"
enum = "Modifier"

[[key]]
label = "Conversion"
code = "Conv"
enum = "Conversion"

[[key]]
label = "Swizzle"
code = "Swizzle"
enum = "Swizzle"

[[key]]
label = "Multiplier"
code = "Mult"
enum = "Multiplier"

[[key]]
label = "Invert"
code = "Invert"
enum = "Invert"
