[[key]]
label = "Storage"
code = "Storage"
enum = "Storage"

[[key]]
label = "Textures"
code = "Texture"
enum = "TextureArray"

[[key]]
label = "Minimization Filter"
code = "MinFilt"
enum = "MinFilter"

[[key]]
label = "Magnification Filter"
code = "MagFilt"
enum = "MagFilter"

[[key]]
label = "Wrap (S)"
code = "WrapS"
enum = "WrapS"

[[key]]
label = "Wrap (T)"
code = "WrapT"
enum = "WrapT"

[[key]]
label = "Generate Mipmaps"
code = "Mipmaps"
enum = "GenerateMipmaps"

[[key]]
label = "Raster"
code = "Raster"
enum = "Raster"

[[key]]
label = "SVG"
code = "SVG"
enum = "SVG"

[[key]]
label = "Image Storage"
code = "ImgStore"
enum = "ImageStorage"

[[key]]
label = "Abstract Storage"
code = "AbsStore"
enum = "AbstractStorage"

[[key]]
label = "Vector Scale"
code = "VecScale"
enum = "VectorScale"

[[key]]
label = "Animated"
code = "Animated"
enum = "Animated"

[[key]]
label = "Rows"
code = "Rows"
enum = "Rows"

[[key]]
label = "Columns"
code = "Columns"
enum = "Columns"

[[key]]
label = "Cell Width Override"
code = "CWOver"
enum = "CellWidthOverride"

[[key]]
label = "Cell Height Override"
code = "CHOver"
enum = "CellHeightOverride"

[[key]]
label = "Delay (cs)"
code = "DelayCS"
enum = "DelayCS"

[[key]]
label = "Row Major"
code = "RowMajor"
enum = "RowMajor"

[[key]]
label = "Row Up"
code = "RowUp"
enum = "RowUp"
