[[key]]
label = "Transformer"
code = "Trfmer"
enum = "Transformer"

[[key]]
label = "Layers"
code = "Layer"
enum = "LayerArray"

[[key]]
label = "Z-Index"
code = "Z"
enum = "Z"

[[key]]
label = "Tile Set"
code = "TileSet"
enum = "TileSet"

[[key]]
label = "Tiles"
code = "Tiles"
enum = "TileArray"

[[key]]
label = "Camera Invariant"
code = "CamInv"
enum = "CameraInvariant"
