[[key]]
label = "Width"
code = "Width"
enum = "Width"

[[key]]
label = "Height"
code = "Height"
enum = "Height"

[[key]]
label = "Title"
code = "Title"
enum = "Title"

[[key]]
label = "Viewport"
code = "Viewport"
enum = "Viewport"

[[key]]
label = "Boxed"
code = "Boxed"
enum = "Boxed"

[[key]]
label = "Stretch"
code = "Stretch"
enum = "Stretch"
