[[key]]
label = "Resizable"
code = "Resize"
enum = "Resizable"

[[key]]
label = "Visible"
code = "Visible"
enum = "Visible"

[[key]]
label = "Clear Color"
code = "ClrColor"
enum = "ClearColor"

[[key]]
label = "Swap Interval"
code = "SwpInt"
enum = "SwapInterval"

[[key]]
label = "Decorated"
code = "Decor"
enum = "Decorated"

[[key]]
label = "Focused"
code = "Focused"
enum = "Focused"

[[key]]
label = "Auto-Iconify"
code = "AutoIcon"
enum = "AutoIconify"

[[key]]
label = "Floating"
code = "Floating"
enum = "Floating"

[[key]]
label = "Maximized"
code = "Maxed"
enum = "Maximized"

[[key]]
label = "Center Cursor"
code = "CCursor"
enum = "CenterCursor"

[[key]]
label = "Transparent Framebuffer"
code = "TrFrmbuf"
enum = "TransparentFramebuffer"

[[key]]
label = "Focus On Show"
code = "FocusOnS"
enum = "FocusOnShow"

[[key]]
label = "Scale To Monitor"
code = "ScaleToM"
enum = "ScaleToMonitor"

[[key]]
label = "Scale Framebuffer"
code = "ScaleFB"
enum = "ScaleFramebuffer"

[[key]]
label = "Mouse Passthrough"
code = "MousePSS"
enum = "MousePassthrough"

[[key]]
label = "Stereo"
code = "Stereo"
enum = "Stereo"

[[key]]
label = "SRGB Capable"
code = "SRGBCap"
enum = "SrgbCapable"

[[key]]
label = "Double-Buffer"
code = "DBuffer"
enum = "DoubleBuffer"

[[key]]
label = "OpenGL Forward Compatible"
code = "FWCompat"
enum = "OpenglForwardCompat"

[[key]]
label = "OpenGL Context Debug"
code = "CTXDebug"
enum = "ContextDebug"

[[key]]
label = "Position (X)"
code = "PosX"
enum = "PositionX"

[[key]]
label = "Position (Y)"
code = "PosY"
enum = "PositionY"

[[key]]
label = "Refresh Rate"
code = "RefreshR"
enum = "RefreshRate"
