[[key]]
label = "Transformer"
code = "Trfmer"
enum = "Transformer"

[[key]]
label = "Border Inner Color"
code = "BIClr"
enum = "BorderInnerColor"

[[key]]
label = "Border Outer Color"
code = "BOClr"
enum = "BorderOuterColor"

[[key]]
label = "Fill Inner Color"
code = "FIClr"
enum = "FillInnerColor"

[[key]]
label = "Fill Outer Color"
code = "FOClr"
enum = "FillOuterColor"

[[key]]
label = "Border"
code = "Border"
enum = "Border"

[[key]]
label = "Border Exponent"
code = "BrdExp"
enum = "BorderExponent"

[[key]]
label = "Fill Exponent"
code = "FillExp"
enum = "FillExponent"

[[key]]
label = "Radius (X)"
code = "RadiusX"
enum = "RadiusX"

[[key]]
label = "Radius (Y)"
code = "RadiusY"
enum = "RadiusY"

[[key]]
label = "Camera Invariant"
code = "CamInv"
enum = "CameraInvariant"
