[[key]]
label = "Enable"
code = "Enable"
enum = "Enable"

[[key]]
label = "Use Logfile"
code = "UseFile"
enum = "UseLogfile"

[[key]]
label = "Use Console"
code = "UseCons"
enum = "UseConsole"

[[key]]
label = "Debug"
code = "Debug"
enum = "Debug"

[[key]]
label = "Info"
code = "Info"
enum = "Info"

[[key]]
label = "Warning"
code = "Warning"
enum = "Warning"

[[key]]
label = "Error"
code = "Error"
enum = "Error"

[[key]]
label = "Fatal"
code = "Fatal"
enum = "Fatal"

[[key]]
label = "Max Prior Log Files"
code = "MxPFiles"
enum = "MaxPriorLogFiles"

[[key]]
label = "Max Prior Log Bytes"
code = "MxPBytes"
enum = "MaxPriorLogBytes"
