[[key]]
label = "Sprite"
code = "Sprite"
enum = "Sprite"

[[key]]
label = "Rows"
code = "Rows"
enum = "Rows"

[[key]]
label = "Columns"
code = "Cols"
enum = "Columns"

[[key]]
label = "Delay (s)"
code = "DelayS"
enum = "DelaySeconds"

[[key]]
label = "Row Major"
code = "RowMajor"
enum = "RowMajor"

[[key]]
label = "Row Up"
code = "RowUp"
enum = "RowUp"

[[key]]
label = "Static Frame"
code = "StatFrm"
enum = "StaticFrame"

[[key]]
label = "Starting Frame"
code = "FrmStart"
enum = "StartingFrame"

[[key]]
label = "Starting Time"
code = "TmStart"
enum = "StartingTime"

[[key]]
label = "Auto Tick"
code = "AutoTick"
enum = "AutoTick"
