[context]
window_hint               = { "clear color" = [0.2, 0.5, 0.8, 1.0] }
window                    = { "width" = 1440, "height" = 1080, "title" = "Olympian Engine" }
"gamepads"                = 1
"signal registries"       = [ "signals.toml" ]
logger                    = { "logfile" = "../../Olympian.log", "append" = true, "console" = true }
"texture registries"      = [ "textures.toml", "grass_tileset.toml" ]
sprite_batch              = { "initial sprites" = 50, "new textures" = 10 }
"sprite registries"       = [ "sprites.toml" ]
polygon_batch             = { "primitives" = 100 }
"polygon registries"      = [ "polygons.toml" ]
ellipse_batch             = { "ellipses" = 100 }
"ellipse registries"      = [ "ellipses.toml" ]
"draw command registries" = [ "draw_commands.toml" ]
"tileset registries"      = [ "grass_tileset.toml" ]
"tilemap registries"      = [ "grass_tilemap.toml" ]
"font face registries"    = [ "fonts.toml" ]
"font atlas registries"   = [ "fonts.toml" ]
text_batch                = { "initial glyphs" = 1000, "new textures" = 10 }
"paragraph registries"    = [ "paragraphs.toml" ]
