[[draw_command]]
"name" = "polygon crop"
"commands" = [
	{ "type" = "draw", "renderable" = "polygon", "name" = "pentagon1" },
	{ "type" = "draw", "renderable" = "polygon", "name" = "pentagon2" },
	{ "type" = "draw", "renderable" = "polygon", "name" = "bordered triangle" },
	{ "type" = "render", "batch" = "polygon" }
]

[[draw_command]]
"name" = "sprite match"
"commands" = [
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite0" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite2" },
	{ "type" = "render", "batch" = "sprite" }
]

[[draw_command]]
"name" = "ellipses"
"commands" = [
	{ "type" = "draw", "renderable" = "ellipse", "name" = "ellipse1" },
	{ "type" = "draw", "renderable" = "ellipse", "name" = "ellipse2" },
	{ "type" = "render", "batch" = "ellipse" }
]

[[draw_command]]
"name" = "sprites, polygons, and tilemaps"
"commands" = [
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite3" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite4" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite5" },
	{ "type" = "render", "batch" = "sprite" },
	{ "type" = "draw", "renderable" = "polygon", "name" = "octagon" },
	{ "type" = "render", "batch" = "polygon" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "sprite1" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "godot icon (10.0)" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "knight" },
	{ "type" = "render", "batch" = "sprite" },
	{ "type" = "draw", "renderable" = "polygon", "name" = "concave shape" },
	{ "type" = "render", "batch" = "polygon" },
	{ "type" = "draw", "renderable" = "sprite", "name" = "spritesheet" },
	{ "type" = "draw", "renderable" = "tilemap", "name" = "grass tilemap" },
	{ "type" = "render", "batch" = "sprite" },
]
