[texture_registry]
"root" = "../textures/grass tileset/"

[[texture_registry.image]]
"file"       = "BE.png"
"name"       = "GT - BE"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "BL.png"
"name"       = "GT - BL"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "BR.png"
"name"       = "GT - BR"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "BT.png"
"name"       = "GT - BT"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "I1.png"
"name"       = "GT - I1"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "I2.png"
"name"       = "GT - I2"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "LE.png"
"name"       = "GT - LE"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "LT.png"
"name"       = "GT - LT"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "M.png"
"name"       = "GT - M"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "RE.png"
"name"       = "GT - RE"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "RT.png"
"name"       = "GT - RT"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "S.png"
"name"       = "GT - S"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "TE.png"
"name"       = "GT - TE"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "TL.png"
"name"       = "GT - TL"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "TR.png"
"name"       = "GT - TR"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[texture_registry.image]]
"file"       = "TT.png"
"name"       = "GT - TT"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[tileset]]
"name" = "grass tileset"
"init" = "discard"

[[tileset.assignment]]
"config" = "S"
"tex"    = "GT - S"

[[tileset.assignment]]
"config" = "M'"
"tex"    = "GT - M"

[[tileset.assignment]]
"config" = "C1'"
"tex"    = "GT - BL"
"uvs"    = [ 0, 0.5, 0, 1 ]

[[tileset.assignment]]
"config" = "C2'"
"tex"    = "GT - BR"

[[tileset.assignment]]
"config" = "C3'"
"tex"    = "GT - TR"

[[tileset.assignment]]
"config" = "C4'"
"tex"    = "GT - TL"

[[tileset.assignment]]
"config" = "T1'"
"tex"    = "GT - LE"

[[tileset.assignment]]
"config" = "T2'"
"tex"    = "GT - BE"

[[tileset.assignment]]
"config" = "T3'"
"tex"    = "GT - RE"

[[tileset.assignment]]
"config" = "T4'"
"tex"    = "GT - TE"

[[tileset.assignment]]
"config" = "E1"
"tex"    = "GT - LT"

[[tileset.assignment]]
"config" = "E2"
"tex"    = "GT - BT"

[[tileset.assignment]]
"config" = "E3"
"tex"    = "GT - RT"

[[tileset.assignment]]
"config" = "E4"
"tex"    = "GT - TT"

[[tileset.assignment]]
"config" = "I1"
"tex"    = "GT - I1"

[[tileset.assignment]]
"config" = "I2"
"tex"    = "GT - I2"
