[[tileset]]
"name" = "grass tileset"
"init" = "discard"

[[tileset.assignment]]
"config" = "S"
"tex"    = "textures/grass tileset/S.png"

[[tileset.assignment]]
"config" = "M'"
"tex"    = "textures/grass tileset/M.png"

[[tileset.assignment]]
"config" = "C1'"
"tex"    = "textures/grass tileset/BL.png"

[[tileset.assignment]]
"config" = "C2'"
"tex"    = "textures/grass tileset/BR.png"

[[tileset.assignment]]
"config" = "C3'"
"tex"    = "textures/grass tileset/TR.png"

[[tileset.assignment]]
"config" = "C4'"
"tex"    = "textures/grass tileset/TL.png"

[[tileset.assignment]]
"config" = "T1'"
"tex"    = "textures/grass tileset/LE.png"

[[tileset.assignment]]
"config" = "T2'"
"tex"    = "textures/grass tileset/BE.png"

[[tileset.assignment]]
"config" = "T3'"
"tex"    = "textures/grass tileset/RE.png"

[[tileset.assignment]]
"config" = "T4'"
"tex"    = "textures/grass tileset/TE.png"

[[tileset.assignment]]
"config" = "E1"
"tex"    = "textures/grass tileset/LT.png"

[[tileset.assignment]]
"config" = "E2"
"tex"    = "textures/grass tileset/BT.png"

[[tileset.assignment]]
"config" = "E3"
"tex"    = "textures/grass tileset/RT.png"

[[tileset.assignment]]
"config" = "E4"
"tex"    = "textures/grass tileset/TT.png"

[[tileset.assignment]]
"config" = "I1"
"tex"    = "textures/grass tileset/I1.png"

[[tileset.assignment]]
"config" = "I2"
"tex"    = "textures/grass tileset/I2.png"
