[[tilemap]]
"name" = "grass tilemap"
"init" = "discard"
transform = { "scale" = [ 100, 100 ] }

[[tilemap.layer]]
"z" = 0
"tileset" = "grass tileset"
"tiles" = [
	[ -1, -1 ],
	[  0, -1 ],
	[  1, -1 ],
	[ -1,  0 ],
	[  1,  0 ],
	[  2,  0 ],
	[ -1,  1 ],
	[  0,  1 ],
	[  1,  1 ],
	[  2,  2 ],
	[  3,  2 ],
	[  2,  3 ],
	[  3,  3 ],
]
