[context]
window_hint          = { "clear color" = [0.2, 0.5, 0.8, 1.0] }
window               = { "width" = 1440, "height" = 1080, "title" = "Olympian Engine" }
"texture registries" = ["texture_registry.toml"]
sprite_batch         = { "initial sprites" = 50, "new textures" = 10 }
"sprite registries"  = ["sprite_registry.toml"]
polygon_batch        = { "primitives" = 100 }
"polygon registries" = ["polygon_registry.toml"]
ellipse_batch        = { "ellipses" = 100 }
"ellipse registries" = ["ellipse_registry.toml"]
