[context]
window_hint = { "clear color" = [0.2, 0.5, 0.8, 1.0] }
window = { "width" = 1440, "height" = 1080, "title" = "Olympian Engine" }
"texture_registries" = ["texture_registry.toml"]
mut_sprite_batch = { "initial sprites" = 50, "new textures" = 10 }
