[emitter]
"period" = 5.0
lifespan_offset_rng = { "type" = "power spike",	"a" = -0.2, "b" = 0.2 }

	[emitter.spawn_rate]
	"type" = "piecewise"
		[[emitter.spawn_rate.subfunctions]]
		"interval"          = [0.0, 3.0]
		"type"              = "continuous pulse"
		"global multiplier" = 10.0
		points = [
			{ "t" = 0.0, "w" =  50, "a" = 0.0, "b" = 0.2 },
			{ "t" = 1.0, "w" = 100, "a" = 0.1, "b" = 0.1 },
			{ "t" = 2.0, "w" =  20, "a" = 0.1, "b" = 0.1 },
			{ "t" = 2.3, "w" =  70, "a" = 0.1, "b" = 0.1 }
		]
		[[emitter.spawn_rate.subfunctions]]
		"interval" = [3.0, 5.0]
		"type"     = "constant"
		"c"        = 500

	[emitter.transform_rng]
		rotation = { "type" = "uniform", "a" = -0.52359877559829887307710723054658, "b" = 0.52359877559829887307710723054658 } # -pi / 6, pi / 6
		scale = { x = { "type" = "uniform", "a" = 4, "b" = 6 }, y = { "type" = "uniform", "a" = 3, "b" = 12 } }
		[emitter.transform_rng.position]
		"position" = [150.0, 200.0]
		"scale"    = [400.0, 250.0]
			[[emitter.transform_rng.position.shapes]]
			"type" = "rect"
			"w"    = 3.0
			transform = { "position" = [-0.5, 0.5], "scale" = [1.0, 0.4] }
				[emitter.transform_rng.position.shapes.fnx]
				"type" = "power spike array"
				spikes = [
					{ "a" =  0.0, "b" = 0.6,                                   "pos" = -1.0 },
					{ "a" = -0.4, "b" = 0.4, "power" = 4.0,                    "pos" =  0.0 },
					{ "a" = -0.4, "b" = 0.2, "power" = 4.0, "inverted" = true, "pos" =  0.8 }
				]
				[emitter.transform_rng.position.shapes.fny]
				"type" = "power spike array"
				spikes = [
					{ "pos" = -1.0 },
					{ "pos" =  1.0 }
				]
			[[emitter.transform_rng.position.shapes]]
			"type" = "ellipse"
			"w"    = 1.0
			transform = { "position" = [0.5, -0.5], "scale" = [0.4, 0.4] }
			fna = { "type" = "uniform" }
			fnr = { "type" = "power spike", "a" = 0.0, "power" = 10.0, "inverted" = true }

	[emitter.color]
	"type"       = "piecewise"
	"last color" = [0.0, 1.0, 0.0, 1.0]
	subfunctions = [
		{ "type" = "constant", "c" = [1.0, 1.0, 1.0, 1.0], "i" =  500 },
		{ "type" = "constant", "c" = [1.0, 0.0, 0.0, 1.0], "i" = 1500 },
		{ "type" = "constant", "c" = [0.0, 0.0, 1.0, 1.0], "i" = 1700 },
		{ "type" = "constant", "c" = [1.0, 0.0, 1.0, 1.0], "i" = 2400 }
	]
