[[sprite]]
"name"    = "sprite0"
"texture" = "textures/einstein.png"
transform = { "position" = [300, 300] }
"init"    = "discard"

[[sprite]]
"name"       = "sprite1"
"texture"    = "textures/einstein.png"
"modulation" = [
	[1.0, 1.0, 0.2, 0.7],
	[0.2, 1.0, 1.0, 0.7],
	[1.0, 0.2, 1.0, 0.7],
	[0.5, 0.5, 0.5, 0.7]
]
"init"       = "discard"

[[sprite]]
"name"             = "sprite2"
"texture"          = "textures/tux.png"
transform          = { "position" = [-100, -100], "scale" = [0.2, 0.2] }
transform_modifier = { "type" = "shear" }
"init"             = "discard"
	
[[sprite]]
"name"       = "sprite3"
"texture"    = "textures/serotonin.gif"
transform    = { "position" = [100, -100], "scale" = [2.0, 2.0] }
frame_format = { "num frames" = 59, "delay seconds" = -0.05 }
"init"       = "discard"

[[sprite]]
"name"          = "sprite4"
"texture"       = "textures/tux.png"
"texture index" = 1
transform       = { "position" = [-500, 300], "scale" = [0.1, 0.1] }
"init"          = "discard"
	
[[sprite]]
"name"    = "sprite5"
"texture" = "textures/tux.png"
transform = { "position" = [-400, 300], "scale" = [0.1, 0.1] }
"init"    = "discard"
	
[[sprite]]
"name"    = "flag instance"
"texture" = "textures/flag.png"
transform = { "scale" = [2.0, 2.0] }
"init"    = "keep"
	
[[sprite]]
"name"      = "godot icon (1.0)"
"texture"   = "textures/godot.svg"
"svg scale" = 1.0
transform   = { "position" = [-300, -200], "rotation" = 0.3, "scale" = [3.0, 3.0] }
"init"      = "discard"
	
[[sprite]]
"name"      = "godot icon (3.0)"
"texture"   = "textures/godot.svg"
"svg scale" = 3.0
transform   = { "position" = [-300, -200], "rotation" = 0.3, "scale" = [1.0, 1.0] }
"init"      = "discard"
	
[[sprite]]
"name"      = "godot icon (10.0)"
"texture"   = "textures/godot.svg"
"svg scale" = 10.0
transform   = { "position" = [-300, -200], "rotation" = 0.3, "scale" = [0.3, 0.3] }
"init"      = "discard"
	
[[sprite]]
"name"       = "knight"
"texture"    = "textures/knight.png"
transform    = { "position" = [100, -300], "scale" = [20, 20] }
frame_format = { "mode" = "auto" }
"init"       = "discard"

[[sprite]]
"name"          = "spritesheet"
"texture"       = "textures/knight.png"
"texture index" = 1
transform       = { "position" = [300, -200], "scale" = [20, 20] }
"init"          = "discard"

[[sprite_atlas]]
"name"          = "atlased knight"
"sprite"        = "spritesheet"
"rows"          = 2
"cols"          = 3
"delay seconds" = 0.1
"init"          = "discard"
