[[image]]
"file"       = "../textures/einstein.png"
"name"       = "einstein"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"
	
[[image]]
"file"       = "../textures/flag.png"
"name"       = "flag"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"
	
[[image]]
"file" = "../textures/tux.png"
		
	[[image.texture]]
	"name"       = "tux"
	"auto-use"   = true
	"min filter" = "linear"
	"mag filter" = "linear"

	[[image.texture]]
	"name"             = "mipmapped tux"
	"generate mipmaps" = true
	"auto-use"         = true
	"min filter"       = "nearest mipmap linear"
	"mag filter"       = "nearest"

[[image]]
"file"       = "../textures/serotonin.gif"
"name"       = "serotonin"
"anim"       = true
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"

[[nsvg_abstract]]
"file"    = "../textures/godot.svg"
"name"    = "godot icon"
"discard" = true

	[[nsvg_abstract.texture]]
	"name"       = "godot icon (1.0)"
	"scale"      = 1.0
	"auto-use"   = true
	"min filter" = "nearest"
	"mag filter" = "nearest"
		
	[[nsvg_abstract.texture]]
	"name"       = "godot icon (3.0)"
	"scale"      = 3.0
	"auto-use"   = true
	"min filter" = "nearest"
	"mag filter" = "nearest"
		
	[[nsvg_abstract.texture]]
	"name"             = "godot icon (10.0)"
	"scale"            = 10.0
	"auto-use"         = true
	"generate mipmaps" = "manual"
	"min filter"       = "nearest mipmap linear"
	"mag filter"       = "nearest"

[[image]]
"file"       = "../textures/knight.png"
"name"       = "knight"
"anim"       = true
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"
"rows"       = 2
"cols"       = 3
"delay cs"   = 10
	
[[image]]
"file"       = "../textures/knight.png"
"name"       = "spritesheet"
"auto-use"   = true
"min filter" = "nearest"
"mag filter" = "nearest"
