[texture_registry]
	"root" = "../textures/"
	
	[[texture_registry.image]]
	"file" = "einstein.png"
	"name" = "einstein"
	"auto-use" = true
	"min filter" = "nearest"
	"mag filter" = "nearest"
	
	[[texture_registry.image]]
	"file" = "flag.png"
	"name" = "flag"
	"auto-use" = true
	"min filter" = "nearest"
	"mag filter" = "nearest"
	
	[[texture_registry.image]]
	"file" = "tux.png"
		
		[[texture_registry.image.texture]]
		"name" = "tux"
		"auto-use" = true
		"min filter" = "linear"
		"mag filter" = "linear"

		[[texture_registry.image.texture]]
		"name" = "mipmapped tux"
		"generate mipmaps" = true
		"auto-use" = true
		"min filter" = "nearest mipmap linear"
		"mag filter" = "nearest"

	[[texture_registry.image]]
	"file" = "serotonin.gif"
	"type" = "gif"
	"name" = "serotonin"
	"auto-use" = true
	"min filter" = "nearest"
	"mag filter" = "nearest"
	