[tileset]
"storage" = "discard"

[[tileset.assignment]]
"config"  = 0
"texture" = "textures/grass tileset/S.png"

[[tileset.assignment]]
"config"  = 46
"texture" = "textures/grass tileset/M.png"

[[tileset.assignment]]
"config"  = 16
"texture" = "textures/grass tileset/BL.png"

[[tileset.assignment]]
"config"  = 17
"texture" = "textures/grass tileset/BR.png"

[[tileset.assignment]]
"config"  = 18
"texture" = "textures/grass tileset/TR.png"

[[tileset.assignment]]
"config"  = 19
"texture" = "textures/grass tileset/TL.png"

[[tileset.assignment]]
"config"  = 28
"texture" = "textures/grass tileset/LE.png"

[[tileset.assignment]]
"config"  = 29
"texture" = "textures/grass tileset/BE.png"

[[tileset.assignment]]
"config"  = 30
"texture" = "textures/grass tileset/RE.png"

[[tileset.assignment]]
"config"  = 31
"texture" = "textures/grass tileset/TE.png"

[[tileset.assignment]]
"config"  = 1
"texture" = "textures/grass tileset/LT.png"

[[tileset.assignment]]
"config"  = 2
"texture" = "textures/grass tileset/BT.png"

[[tileset.assignment]]
"config"  = 3
"texture" = "textures/grass tileset/RT.png"

[[tileset.assignment]]
"config"  = 4
"texture" = "textures/grass tileset/TT.png"

[[tileset.assignment]]
"config"  = 9
"texture" = "textures/grass tileset/I1.png"

[[tileset.assignment]]
"config"  = 10
"texture" = "textures/grass tileset/I2.png"
