#meta version=1.0 type="particle_system"

[emitter0]
	[emitter0.Spawner]
	Klass = "ConstantParticleSpawner"

	[emitter0.Color]
		[emitter0.Color.Domain]
			[emitter0.Color.Domain.C]
			Op = 0
				[[emitter0.Color.Domain.C.Ops]]
				Op = 1
				Selector = 1
					[emitter0.Color.Domain.C.Ops.InnerOp]
					Op = 2
					A = 0.5
					B = 2.0
					K = 1.57
					C = 0.5
				[[emitter0.Color.Domain.C.Ops]]
				Op = 1
				Selector = 3
					[emitter0.Color.Domain.C.Ops.InnerOp]
					Op = 2
					A = 0.5
					B = 2.0
					K = 0.57
					C = 0.5

	[emitter0.Velocity]
		[emitter0.Velocity.Domain]
			[emitter0.Velocity.Domain.C]
			Op = 3
			Amp = 100.0

[emitter1]
	[emitter1.Color]
		[emitter1.Color.Domain]
			[emitter1.Color.Domain.C]
			Value = [0.0, 0.0, 1.0, 1.0]
