index_type = "unsigned int"
enum_type = "oly::rendering::TileSet::Transformation"
default = 0

[[enum]]
label = "None"
index = 0
enum = 0b00000
comment = "Transformation::None"

[[enum]]
label = "Reflect (X)"
index = 1
enum = 0b00001
comment = "Transformation::ReflectX"

[[enum]]
label = "Reflect (Y)"
index = 2
enum = 0b00010
comment = "Transformation::ReflectY"

[[enum]]
label = "Rotate (90)"
index = 3
enum = 0b00100
comment = "Transformation::Rotate90"

[[enum]]
label = "Rotate (180)"
index = 4
enum = 0b01000
comment = "Transformation::Rotate180"

[[enum]]
label = "Rotate (-90)"
index = 5
enum = 0b10000
comment = "Transformation::Rotate270"
