#meta type=archetype

[archetype]
name = "BKG"
draw = [
	"bkg_rect"
]
"singleton" = "true"

[[archetype.polygon]]
name = "bkg_rect"
"points" = [
	[ -1, -1 ],
	[  1, -1 ],
	[  1,  1 ],
	[ -1,  1 ]
]
"colors" = [
	[ 0.2, 0.5, 0.8, 1.0 ]
]
transform = { "scale" = [ 1440, 1080 ] }
