#meta type=archetype

[archetype]
draw = [
	"sprite0",
	"sprite2"
]

[sprite0]
transform = { "position" = [450, -200] }
"texture" = "~/textures/einstein.png"

[sprite2]
"texture" = "~/textures/tux.png"
transform = { "position" = [-100, -100], "scale" = [0.2, 0.2], modifier = { "type" = "shear" } }
