#meta type=archetype

[archetype]
name = "SpriteMatch"
draw = [
	"sprite0",
	"sprite2"
]

[[archetype.sprite]]
name = "sprite0"
transform = { "position" = [450, -200] }
"texture" = "textures/einstein.png"

[[archetype.sprite]]
name = "sprite2"
"texture" = "textures/tux.png"
transform = { "position" = [-100, -100], "scale" = [0.2, 0.2] }
transform_modifier = { "type" = "shear" }
