#meta version=1.0 type=archetype

[archetype]
draw = [
	"sprite0",
	"sprite2"
]

[sprite0]
Trfmer = { Position = [450, -200] }
Texture = "@/textures/einstein.png"

[sprite2]
Texture = "@/textures/tux.png"
Trfmer = { Position = [-100, -100], Scale = [0.2, 0.2], Modifier = { Klass = "ShearTransformModifier2D" } }
