#meta version=1.0 type=archetype

[archetype]
draw = [
	"sprite0",
	"sprite2"
]

[sprite0]
transformer = { Position = [450, -200] }
texture = "@/textures/einstein.png"

[sprite2]
texture = "@/textures/tux.png"
transformer = { Position = [-100, -100], Scale = [0.2, 0.2], Modifier = { "type" = 1 } }
