site_name: Olympian Engine Docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Engine:
    - Overview: engine/Overview.md
    - Rendering:
      - Geometry Painter: engine/rendering/GeometryPainter.md
      - Paint Support: engine/rendering/PaintSupport.md
    - Physics:
      - Dynamics:
        - Rigid Body: engine/physics/dynamics/RigidBody.md
        - Static Body: engine/physics/dynamics/StaticBody.md
        - Linear Body: engine/physics/dynamics/LinearBody.md
        - Kinematic Body: engine/physics/dynamics/KinematicBody.md
  - Editor:
    - Overview: editor/Overview.md
