site_name: Olympian Engine Docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

nav:
  - Home: index.md
  - Engine:
    - Overview: engine/Overview.md
    - Physics:
      - Dynamics:
        - Rigid Body: engine/physics/dynamics/RigidBody.md
    - Rendering:
      - Particles:
        - Samplers: engine/rendering/particles/Samplers.md
  - Editor:
    - Overview: editor/Overview.md
