[image]
storage = "discard"
"min filter" = "nearest"
"mag filter" = "nearest"
"generate mipmaps" = false

[gif]
storage = "discard"
"min filter" = "nearest"
"mag filter" = "nearest"
"generate mipmaps" = false

[svg]
"abstract storage" = "discard"
"image storage" = "discard"
"min filter" = "linear"
"mag filter" = "linear"
"generate mipmaps" = "off"
